# -*- coding: utf-8 -*-
"""Sales analysis_syntexchub

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOMNuuz78SMgatCNzlDDJZmt_6EBOFC9
"""

# Commented out IPython magic to ensure Python compatibility.
# Core libraries
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Settings
# %matplotlib inline
sns.set(style="whitegrid")

from google.colab import files
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])

# Shape of data
print("Dataset Shape:", df.shape)

# Data info
df.info()

# Check missing values
df.isnull().sum()

# Statistical summary
df.describe(include='all').T

# Normalize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.columns

# Use correct date column name
df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

df = df.dropna(subset=['date', 'quantity', 'unit_price'])

df['revenue'] = df['quantity'] * df['unit_price']

df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['month_name'] = df['date'].dt.month_name()

# Total Revenue
total_revenue = df['revenue'].sum()

# Number of Orders
orders = df['order_id'].nunique()

# Average Order Value
aov = total_revenue / orders

print(f"Total Revenue: ₹{total_revenue:,.2f}")
print(f"Total Orders: {orders}")
print(f"Average Order Value (AOV): ₹{aov:,.2f}")

top_products = (
    df.groupby('product')
      ['revenue']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_products

plt.figure(figsize=(10,5))
top_products.plot(kind='bar')
plt.title('Top 10 Products by Revenue')
plt.ylabel('Revenue')
plt.xlabel('Product')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

top_regions = (
    df.groupby('region')
      ['revenue']
      .sum()
      .sort_values(ascending=False)
)

top_regions.head()

plt.figure(figsize=(8,5))
top_regions.head(10).plot(kind='bar')
plt.title('Top Regions by Revenue')
plt.ylabel('Revenue')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df.set_index('date', inplace=True)

monthly_sales = df['revenue'].resample('M').sum()

plt.figure(figsize=(10,4))
monthly_sales.plot()
plt.title('Monthly Revenue Trend')
plt.ylabel('Revenue')
plt.xlabel('Month')
plt.tight_layout()
plt.show()

seasonality = df.groupby(df.index.month)['revenue'].sum()

plt.figure(figsize=(8,4))
seasonality.plot(kind='bar')
plt.title('Revenue by Month (Seasonality)')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.tight_layout()
plt.show()

plt.figure(figsize=(11,8))

# KPIs
plt.subplot(2,2,1)
plt.axis('off')
kpi_text = (
    f"Total Revenue: ₹{total_revenue:,.0f}\n"
    f"Orders: {orders}\n"
    f"AOV: ₹{aov:,.0f}\n"
    f"Top Product: {top_products.index[0]}"
)
plt.text(0.1, 0.5, kpi_text, fontsize=14)

# Monthly Trend
plt.subplot(2,2,2)
monthly_sales.plot()
plt.title('Monthly Revenue Trend')

# Top Products
plt.subplot(2,2,3)
top_products.plot(kind='barh')
plt.title('Top Products')

# Regions
plt.subplot(2,2,4)
top_regions.head(5).plot(kind='bar')
plt.title('Top Regions')

plt.tight_layout()
plt.savefig('one_page_summary.png', dpi=200)
plt.show()

df.reset_index().to_csv('cleaned_sales_data.csv', index=False)